Fixed login
openMF/web-self-service-app pull request #183
Opened 2022-01-10 12:25 UTC by rrpawar96

This PR fixes the issue of Login, instead of sending parameters from headers it sends from JSON body: addresses- [FINERACT-726](https://issues.apache.org/jira/browse/FINERACT-726)  

This PR also resolves the PR of redirecting issue, after successful login now it redirects to the dashboard.

This PR also resolves the issue where if we refresh one tab then data of other tabs also getting refreshed, so it will stop that

2022-03-04 14:34 UTC, rrpawar96 commented
@avikganguly01, Please review and merge this PR.

2022-03-05 11:26 UTC, francisguchie commented
@avikganguly01 @rrpawar96 I am interested in testing this

2022-03-05 11:56 UTC, avikganguly01 requested changes

2022-03-05 11:56 UTC, avikganguly01 commented on app/app.constants.js
> +        .constant("tenantIdentifier", "default")
What is the purpose of defining the tenantIdentifier 3 times here?

2022-03-05 11:56 UTC, avikganguly01 commented on app/src/authentication/authentication.service.js
> +       /* var setAccessToken = function (token) {
Can these comments be removed if it's no longer relevant?

2022-03-05 22:11 UTC, rrpawar96 commented
@avikganguly01, Thanks for the review, Comments Addressed, Please re-review.

2023-05-18 23:02 UTC, francisguchie commented
@avikganguly01 
would this be merged soon?

2023-05-20 16:39 UTC, francisguchie commented
@avikganguly01 @vishwasbabu can this be reviewed please and merged

2023-05-20 16:55 UTC, avikganguly01 approved these changes

2023-05-20 16:56 UTC, merged